apiVersion: apps/v1
kind: Deployment
metadata:
  name: wholesale-segmentation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wholesale-segmentation
  template:
    metadata:
      labels:
        app: wholesale-segmentation
    spec:
      containers:
      - name: wholesale-segmentation
        image: nikhilraman12/wholesale-segmentation:latest
        ports:
        - containerPort: 7860