apiVersion: v1
kind: Service
metadata:
  name: wholesale-segmentation-service
spec:
  type: NodePort
  selector:
    app: wholesale-segmentation
  ports:
    - protocol: TCP
      port: 7860
      targetPort: 7860
      nodePort: 30081   # <-- changed to a free port